### PR TITLE
Create Mid Point Line Drawing Algorithm

### PR DESCRIPTION
**Pull request by Ankit-2312**
Update For The Project Collaboration. Do add the other files too.
Thanks @AKGBJN

#UPDATED

### CODE REVIEW

**Comment by AKGBJN** [comment]
Ok thanks

**Comment by AKGBJN** [comment]
Is this code working

**Comment by Ankit-2312** [comment]
Yes, obviously

**Comment by AKGBJN** [comment]
Ok, merged

**Pull request merged**
